services:

  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - '8000:8000'


  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - '8501:8501'
    depends_on:
      - backend